# Generated by Django 3.1.3 on 2021-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='uuid',
        ),
        migrations.AddField(
            model_name='url',
            name='short_query',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
