# Generated by Django 3.1.3 on 2021-06-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20210627_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='ShortUrl',
        ),
    ]
