# Generated by Django 3.1.3 on 2021-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20210627_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(default=''),
        ),
    ]
